### ISSUE TITLE
Complex types in Parquet storage format

### ISSUE THREAD

**Issue by morazow** [exasol/cloud-storage-extension#11]
Exasol does not support complex types such as `Map`, `Struct` or `Array`. 

Therefore, it is important how to support complex types in Parquet or Avro formats.

One possible option is to converting them into json string and to store them as a `VARCHAR` in Exasol table.

**Comment by mandeva255** [comment]
This enhancement is required as it is requirement now a days a lot . Data format and structure is getting changed.

**Comment by tkilias** [comment]
@morazow another option would be a parameter which allows to specify a mapping from complex type to columns, similar to the DynamoDB virtual schema

**Comment by morazow** [comment]
Hello @mandeva255,

Thanks for the feedback! It is good that there is interest for this feature!

Recently, @jwarlander also looked into support for Array types, but it was in the context of Kafka consumer.

@tkilias since here we can usually have `list`, `map` like structures, I was thinking to map them to Exasol `VARCHAR` with user provided varchar size.

**Comment by jwarlander** [comment]
I'd agree with @morazow, if we import initially as JSON fields then a subsequent step in Exasol can extract whatever is needed from the JSON fields into actual table fields.. Will see if I can get that done, at least for Avro for now, as I have a need for it myself.
