### ISSUE TITLE
S3 connection syntax

### ISSUE THREAD

**Issue by drumcircle** [exasol/cloud-storage-extension#128]
Updated to the latest release 1.0.0.

Now, the IMPORT_PATH facility uses a CONNECTION vs credentials.

I create a connection and am using the string pattern described in docs.  Now getting this error.

[Code: 0, SQL State: 22002]  VM error: F-UDF-CL-LIB-1127: F-UDF-CL-SL-JAVA-1002: F-UDF-CL-SL-JAVA-1013: 
com.exasol.ExaUDFException: F-UDF-CL-SL-JAVA-1080: Exception during run 
java.lang.IllegalArgumentException: Connection object password does not contain key=value pairs!
com.exasol.common.AbstractProperties.$anonfun$parseConnectionInfo$1(AbstractProperties.scala:81)
scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:285)
scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)

CREATE CONNECTION S3_DEV_SANDBOX
TO 'https://BUCKET.s3.REGION.amazonaws.com'
USER 'ACCESSKEY'
IDENTIFIED BY  'SECRETKEY';

IMPORT INTO DEV_SANDBOX.TABLE
FROM SCRIPT  ETL.IMPORT_PATH
WITH 
BUCKET_PATH ='s3a://BUCKET/PATHTOFILES'
DATA_FORMAT = 'AVRO'
CONNECTION_NAME = 'S3_DEV_SANDBOX'
S3_ENDPOINT = 's3.us-east-2.amazonaws.com' 
PARALLELISM = 'nproc()*4';

**Comment by morazow** [comment]
Hello @drumcircle,

Yes, couple releases back we changed the encoding of the credentials. 

Please update the connection object as described in [S3 - Create Connection Object](https://github.com/exasol/cloud-storage-extension/blob/main/doc/user_guide/user_guide.md#create-exasol-connection-object).

The main rationale behind using the `key=value` separated credentials, is it provide additional credentials. For example, to access the S3 some accounts may require session token. 
Similarly, other cloud storage systems (Azure, GCP) require additional keys (directory id, client id, etc).

**Comment by drumcircle** [comment]
Now all clear, thank you.
________________________________
