### ISSUE TITLE
HASHTYPE destination column not supported

### ISSUE THREAD

**Issue by drumcircle** [exasol/cloud-storage-extension#130]
I received import errors when landing data into tables with HASHTYPE columns.

Changing these to VARCHAR worked.

RESPONDENTID HASHTYPE (16 BYTE) 
fail

RESPONDENTID VARCHAR(50) 
works

**Comment by morazow** [comment]
Hello @drumcircle,

Thanks for the feedback!

We can look into it. What data type would correspond to the Exasol HASHTYPE? For example, are importing Parquet Binary or Avro Bytes data into Hashtype?

**Comment by drumcircle** [comment]
In most solutions, GUIDs come across as simple strings.  String is compatible with HashType if it uses the right character-set.  This is an example where introspecting the target and casting would make the solution more robust.

**Comment by drumcircle** [comment]
Export also fails for the same reason (using 1.3.1)

**Comment by morazow** [comment]
Hello @drumcircle,

Thanks for the feedback!

We had internally discussed support for Hashtype in cloud-storage-extension which are based on Exasol UDF. Unfortunately, the communication between database and UDF will never support the Hashtype data types. Exasol Hashtype datatype are stored as bytes, and they become tricky to manage (e.g, endiannes) once outside the database.

I am going to close the ticket soon.
