### ISSUE TITLE
AVRO duplicate/missing records

### ISSUE THREAD

**Issue by drumcircle** [exasol/cloud-storage-extension#144]
Things were going well until we started wildcard matching huge numbers of files on S3 and then noticed some discrepancies in landing data.  We were loading into a cluster of 2 nodes with parallelism of 4.  Based on prior experience, I'm doubting this was the problem but wondering if anything you have seen could explain discrepancies with bulk loading AVRO in parallel.

**Comment by morazow** [comment]
Hello @drumcircle,

Loading multiple files should be possible. Could you please tell what kind discrepancies you seeing? Is it duplicated records, or missing records?

I do not think we had such issues with increased parallelism.

**Comment by morazow** [comment]
Hello @drumcircle,

Can I help you with this issue? Or would it be okay to close this Github issue ticket?

**Comment by redcatbear** [comment]
No response in 18 days. Closing issue.
