### ISSUE TITLE
Delimited identifiers

### ISSUE THREAD

**Issue by allipatev** [exasol/cloud-storage-extension#145]
Hi,
Cloud storage extension doesn't seem to support delimited identifiers:
```sql
create or replace table test.delimited_identifier(
"col1" varchar(100)
);

EXPORT test.delimited_identifier
INTO SCRIPT CLOUD_STORAGE_EXTENSION.EXPORT_PATH WITH
  BUCKET_PATH     = 's3a://<S3_PATH>/'
  DATA_FORMAT     = 'PARQUET'
  S3_ENDPOINT     = 's3.<REGION>.amazonaws.com'
  CONNECTION_NAME = 'S3_CONNECTION'
  PARALLELISM     = 'iproc()';

-- SQL Error [42000]: object COL1 not found [line 3, column 195] (Session: 1697028889144223990)
```
Is it possible to fix it?
If yes, IMPORT_PATH might also have such a problem - it's hard for me to check as I could not export.

**Comment by morazow** [comment]
Hello @allipatev,

Thanks for the feedback! Yes, this is known issue for the export. I am going to plan it for the coming weeks.

It should not be problem in import.
