### ISSUE TITLE
Enable "CREATE TABLE AS SELECT ... from (IMPORT FROM SCRIPT ...)"

### ISSUE THREAD

**Issue by MaselEOBHH** [exasol/cloud-storage-extension#147]
We use GoogleCloudStorage for a kind of staging area and want to blend those data into the exasol. This works properly when the schema is known (which mostly not the case), but it would be easier to be able to use the fancy syntax:
```
create table [myschema].[mytable] as select * from 
(
import from script CLOUD_STORAGE_EXTENSION.IMPORT_PATH WITH
...
...
)
```
But this results in the following error:
`SQL-Fehler [42000]: The script has dynamic return arguments. Either specify the return arguments in the query via EMITS or implement the method getDefaultOutputColumns in the UDF`

If it is easy to do this improvement, one could easy get insight of parquet-files without knowing the structure of them.

**Comment by morazow** [comment]
Hello @MaselEOBHH,

Unfortunately you cannot use `IMPORT` statement as a subselect.

But you can use the `IMPORT_FILES` script you prepare in the deployment to import per file. It is not intended to be run manually, but you can use it. 

However, you will have to prepare the input to the script yourself.

For example:
```
SELECT * FROM (
   SELECT ETL.IMPORT_FILES(
             's3://path/*',
             'DATA_FORMAT -> ORC;CONNECTION_NAME -> S3_CONNECTION;BUCKET_PATH -> s3://path/*',
             's3://path/filename01.orc'
   )
);
```

**Comment by redcatbear** [comment]
No reply in 18 days. Closing ticket.
