### ISSUE TITLE
Enable SSL for S3 import

### ISSUE THREAD

**Issue by morazow** [exasol/cloud-storage-extension#184]
### Acceptance Criteria

- Add a parameter to enable the SSL for S3 import
- ~Enable it by default~ (already enabled by default)

**Comment by nicornk** [comment]
@morazow Isn't SSL automatically used when using s3a filesystem?

**Comment by morazow** [comment]
Hey @nicornk,

Yes, it is. I added [tests](https://github.com/exasol/cloud-storage-extension/pull/186/files#diff-b3cc29e036d344dc97b6079577c72e3ee90d434525d2d805a1a89d22ca1290dfR94-R97) to confirm it. Also, added parameter in cases (hopefully rare) to disable it.
