### ISSUE TITLE
Parallelism examples

### ISSUE THREAD

**Issue by allipatev** [exasol/cloud-storage-extension#213]
It seems that together with the latest release [2.4.0: Support for automatic parallelism](https://github.com/exasol/cloud-storage-extension/releases/tag/2.4.0) examples of manual parallelism settings were removed from [User Guide](https://github.com/exasol/cloud-storage-extension/blob/main/doc/user_guide/user_guide.md).

Guessing right values for PARALLELISM parameter is, obviously, hard, if possible.

As you have seen from the recent tickets (SUPPORT-34484), tuning PARALLELISM parameter might be often needed for small tables to avoid having, for example, too many single-row files.

Please consider returning back the explanation of typical PARALLELISM parameter values for IMPORT_PATH and EXPORT_PATH scripts.

**Comment by morazow** [comment]
Hey @allipatev,

Thanks for the feedback!

Yes, we removed it from docs intentionally. But maybe good idea to bring it back and update it with examples from the support ticket. I will do it in our next bug fixing week.
