### ISSUE TITLE
Upgrade to latest version of com.exasol:import-export-udf-common-scala_2.13

### ISSUE THREAD

**Issue by kaklakariada** [exasol/cloud-storage-extension#225]
The latest version of com.exasol:import-export-udf-common-scala_2.13 contains incompatible API changes.
We should upgrade to the latest version and adapt to the new API.

**Comment by ckunki** [comment]
This is even more urgent, as version 0.2.0 currently used contains a transitive dependency to `com.exasol:exasol-script-api` which had been published to discontinued maven repository `maven.exasol.com`. Without updating `com.exasol:import-export-udf-common-scala` builds will fail.

```
com.exasol:cloud-storage-extension:jar:2.6.2
\- com.exasol:import-export-udf-common-scala_2.13:jar:0.2.0:compile
   \- com.exasol:exasol-script-api:jar:6.1.7:compile
```
