### ISSUE TITLE
Add advice about IMPORT to documentation

### ISSUE THREAD

**Issue by ckunki** [exasol/cloud-storage-extension#234]
The current ticket requests to update documentation of cloud-storage-extension to 
* mention alternative ways for data import
* focus links to additional important documentation 

### Background 
Besides using the cloud-storage-extension (CSE) users should consider direct import which usually is much faster and even supports `PARALLELISM`, e.g. when importing multiple files and import does not require a specific ordering. 

### Existing documentation

Currently the [official documentation](https://docs.exasol.com/db/latest/sql/import.htm#cloud_connection_def) already contains instructions for Azure
```sql
IMPORT INTO table1 FROM CSV AT 
CLOUD AZURE BLOBSTORAGE 'DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net' 
USER '<AccountName>' IDENTIFIED BY '<AccountKey>' FILE '<container>/<blob>'
```

However the page contains instructions for generic http or https with option `file_src` and more information is available in other places 
* https://docs.exasol.com/db/latest/loading_data/load_data_google_cloud_storage_buckets.htm 
* https://github.com/exasol/connection-parameter-specification/blob/main/specification.md 

### Rationale
The current ticket is inspired by support ticket L3-561 and in addition to doc ticket DOC-2424 to improve documentation.

**Comment by morazow** [comment]
Hello @ckunki,

Thanks for the feedback!

The above issue is for CSV format. CSV import is not supported in cloud-storage-extension.

The cloud-storage-extension is for binary Parquet, Avro and ORC formats. In the user guide we have overview of the supported format and supported cloud storage systems.

I am not sure if we need to add any more information without confusing the users.
