### ISSUE TITLE
Documentation for S3_ENDPOINT_REGION

### ISSUE THREAD

**Issue by allipatev** [exasol/cloud-storage-extension#250]
Please consider adding to the User guide the S3_ENDPOINT_REGION parameter added in release [2.5.0](https://github.com/exasol/cloud-storage-extension/releases/tag/2.5.0).

**Comment by morazow** [comment]
Also add examples for S3 compatible storages also:
- For minio endpoint should be `http://minio.yourdomain.tld:4566`
- For foundty endpoint should be `https://<subdomain>.palantircloud.com/io/s3`
