### ISSUE TITLE
Support for presigned URLs

### ISSUE THREAD

**Issue by allipatev** [exasol/cloud-storage-extension#259]
By default, all Amazon S3 objects are private, only the object owner has permission to access them. However, the object owner may share objects with others by creating a presigned URL ([docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html)).

Currently Cloud Storage Extension doesn't support presigned URLs and requires a connection object with credentials.

Please consider implementing support for presigned URLs.

**Comment by ShadyD45** [comment]
Hi @morazow , I'm trying to use the export that is mentioned here https://docs.exasol.com/db/latest/sql/export.htm with minio. Does this support it? And can we the presigned url here? 
Thanks for help

**Comment by allipatev** [comment]
Hi @ShadyD45.

Presigned AWS URLs are supported only for IMPORT command (see [CHANGELOG: IMPORT allows accessing public files and presigned URLs from Amazon S3](https://exasol.my.site.com/s/article/Changelog-content-15504)). IMPORT from presigned URLs for S3-compatible services could work, but this setup is not being actively tested.

The rest could be discussed in a Support ticket 😉

**Comment by redcatbear** [comment]
Closing this ticket, since this feature is not on the roadmap.
