### ISSUE TITLE
FilesMetadataEmitter reports wrong file count when importing multiple files

### ISSUE THREAD

**Issue by kaklakariada** [exasol/cloud-storage-extension#270]
When importing files from a folder (`s3a://bucket/path/folder`) or using a glob (`s3a://bucket/path/file-0*`), class `FilesMetadataEmitter` logs a wrong file count. The count is always one more than the actual file count:

```
[main] INFO com.exasol.cloudetl.emitter.FilesMetadataEmitter - Found total of '101' files in path 's3a://bucket/path*'.
```

When importing a single file, `FilesMetadataEmitter` logs correctly `Found total of '1' files in path 's3a://bucket/path/file.parquet'.`
```[tasklist]
### Tasks
- [ ] Reproduce the problem
```

**Comment by Shmuma** [comment]
Cannot reproduce this issue. Even on s3 bucket, connector shows proper amount of files in the logs
