### ISSUE TITLE
Infer schema from parquet files

### ISSUE THREAD

**Issue by tm-henningnt** [exasol/cloud-storage-extension#293]
It would be very usefull to automatically infer a valid table ddl based on an input parquet (and other) files, both as an automatic capabilitity (i.e. automatically drop/create tables when importing a file), and as a separate capability (i.e. generate a propopsed target table based on an input file).

**Comment by ThomasBestfleisch** [comment]
@tm-henningnt   You can achieve this functionality with Exasol file based virtual schemas where we support auto inference for both CSV & Parquet files. See https://github.com/exasol/virtual-schema-common-document/blob/main/doc/user_guide/edml_user_guide.md#automatic-mapping-inference
