### ISSUE TITLE
CSE: Add tests with Exasol DB V8

### ISSUE THREAD

**Issue by ckunki** [exasol/cloud-storage-extension#312]

**Comment by kaklakariada** [comment]
Integration tests with Exasol v8 were added in https://github.com/exasol/cloud-storage-extension/commit/aec80bf09edcb3fb4b85b346787afbbfc0b736ae#diff-68ba9d12f6f2601fe3c9f7f9d0d02aaea52384559d6d08fae7afc941663fdfcd
