### ISSUE TITLE
Create a mapping between file formats and dependencies they require

### ISSUE THREAD

**Issue by Shmuma** [exasol/cloud-storage-extension#319]
As a first step in CSE simplification, we need to understand what's the dependencies 
pulled by each file format/cloud platform we support. 

The result of the task should be the document with list of data formats (parquet, delta, orc, etc) and short description how they are implemented in CSE (with code links) and list of dependencies which are pulled by this implementation.

Out-of-scope:
* optimisation of dependencies

**Comment by Shmuma** [comment]
https://exasol.atlassian.net/wiki/spaces/InTeam/pages/821428240/File+formats+to+dependencies+mapping

**Comment by kaklakariada** [comment]
Review approved ✅
