### ISSUE TITLE
Ignore Hadoop hidden files

### ISSUE THREAD

**Issue by morazow** [exasol/cloud-storage-extension#35]
As a user of cloud-storage-etl-udfs, 
I want to ignore the Hadoop hidden files which usually start with underscore, e.g, `_SUCCESS`.

**Comment by belenaj** [comment]
Hi @morazow 
somehow this seems still not fixed in version v0.6.1 (ETL.IMPORT_PATH function at least)

Kind regards,
Jorge

**Comment by morazow** [comment]
Hey @belenaj,

Thanks for providing the feedback!

I am goign to check it. Could you please confirm it does not ignore the `_SUCCESS` file (or any file starting with `_`)?

**Comment by belenaj** [comment]
Hi @morazow 
with version 0.6.1:

Below example works fine and ignores files starting with `_`
```
IMPORT INTO RETAIL.SALES_POSITIONS
FROM SCRIPT ETL.IMPORT_PATH WITH
  BUCKET_PATH     = 's3a://<BUCKET>/import/orc/sales_positions/*'
  DATA_FORMAT     = 'ORC'
  S3_ENDPOINT     = 's3.<REGION>.amazonaws.com'
  CONNECTION_NAME = 'S3_CONNECTION'
  PARALLELISM     = 'nproc()*2';
```

however, this statement (removing *) does not ignore `_`, it gives an error:
```
IMPORT INTO RETAIL.SALES_POSITIONS
FROM SCRIPT ETL.IMPORT_PATH WITH
  BUCKET_PATH     = 's3a://<BUCKET>/import/orc/sales_positions/'
  DATA_FORMAT     = 'ORC'
  S3_ENDPOINT     = 's3.<REGION>.amazonaws.com'
  CONNECTION_NAME = 'S3_CONNECTION'
  PARALLELISM     = 'nproc()*2';
```
 ` java.lang.RuntimeException: s3a://pfm-outbound/dbc-exasol/dev/pfm-attr-csta-aggr-exec-summary/year=2019/month=10/day=6/_SUCCESS is not a Parquet file (too small length: 0)
`
It is not a big issue, but I thought it was worth mentioning it.

Regards,
Jorge

**Comment by morazow** [comment]
Hello @belenaj,

Thanks for the input! We are going to look into it. We will try to find what is behaving differently when the glob star is not provided.
