### ISSUE TITLE
Unable to import into a table that resides in a schema that has a limited identifier name

### ISSUE THREAD

**Issue by frschwab** [exasol/cloud-storage-extension#49]
Wheny trying to import into a schema that has a case sensitive name (limited identifier), the UDF seems not to consider this, and doesn't find the schema (the error message says it wants to import into the case-insensitive (uppercased) schema name.
`[Code: 0, SQL State: 42000]  object AAAA_BBBB_CCCC.DDDDD_EEEEEEEEE not found [line 1, column 13] (Session: 1649468587879417167)  [Script position: 2133 - 2134]    IMPORT INTO "aaaa_bbbb_cccc".DDDDD_EEEEEEEEE
FROM SCRIPT ETL.IMPORT_PATH WITH
  BUCKET_PATH          = 'wasbs://ff-ggg@x.blob.core.windows.net/y/z/*'
  DATA_FORMAT          = 'PARQUET'
  AZURE_ACCOUNT_NAME   = 'x'
  AZURE_CONTAINER_NAME = 'ff-ggg'
  AZURE_SAS_TOKEN      = '?sv=...'
  PARALLELISM          = 'nproc()'`

**Comment by morazow** [comment]
Hello @frschwab,

Thanks for reporting this issue! 

We looked into it and decided it is an actual bug. You can check the SPOT-9131 ticket for following this issue.

Meanwhile, please use the regular schema names.

**Comment by morazow** [comment]
@frschwab, I am going to close this ticket, since it is not related to extension, but to database. And now it should be resolved.
