### ISSUE TITLE
Import s3 paths longer than 200 characters

### ISSUE THREAD

**Issue by belenaj** [exasol/cloud-storage-extension#89]
At the moment, it is not possible to import _(potentially neither export, but not tested)_ s3 paths longer than 200 characters.

The process returns below error:
```
java.lang.Exception: Error: [22002] VM error: data exception - string data, right truncation: max length: 200, emitted: 222 
```
Example:

```
IMPORT INTO myschema.mytable
FROM SCRIPT ETL.IMPORT_PATH WITH
BUCKET_PATH    = 's3a://my-very-long-bucket/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-my-very-long-path-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb/cccccccccccccccccccccccccccccc/with-subprojects/mytable/year=2020/month=04/day=02'
DATA_FORMAT    = 'PARQUET'
CONNECTION_NAME = 'MYCONNECTION'
S3_ENDPOINT    = 's3-eu-west-1.amazonaws.com'
PARALLELISM    = 'nproc()';
```

We have tried to reduce the length of the path, but sometimes due to project hierarchy or dependencies on other teams this is not possible.

Kindly extend this limitation if possible.

Thanks and regards,
Jorge

**Comment by belenaj** [comment]
Could this be solved just by increasing the value while deploying the scripts?
```
CREATE OR REPLACE JAVA SCALAR SCRIPT IMPORT_METADATA(...)
EMITS (filename VARCHAR(500), partition_index VARCHAR(100)) AS
  %scriptclass com.exasol.cloudetl.scriptclasses.ImportMetadata;
  %jar /buckets/bfsdefault/bucket1/cloud-storage-etl-udfs-<VERSION>.jar;
/
```
Ref: https://github.com/exasol/cloud-storage-etl-udfs/blob/c87eaac1eb41a744b6a109217b115ccc470bbf6a/docs/deployment_guide.md#create-etl-udfs-scripts

**Comment by morazow** [comment]
Hey @belenaj,

Yes, that is correct.

The first error is also from metadata, right? You can increase the varchar size for the emitted filenames.
