### ISSUE TITLE
CLoud ETL udf documentation does not match release file structure

### ISSUE THREAD

**Issue by LennartAtExasol** [exasol/cloud-storage-extension#96]
https://github.com/exasol/cloud-storage-etl-udfs/blob/master/doc/deployment_guide.md
is using different file versioning than released files. 

Example:
Release file name: exasol-cloud-storage-extension-0.8.0.jar
Docs say:  curl -X PUT -T cloud-storage-etl-udfs-<VERSION>.jar \
  http://w:write-password@exasol.datanode.domain.com:2580/bucket1/**cloud-storage-etl-udfs-<VERSION>.jar**

**Comment by morazow** [comment]
Hello @LennartAtExasol ,

Thanks for the feedback!

Yes, after the last release lot of documentation is obsolete. Once the moving the [Kafka](https://github.com/exasol/kafka-connector-extension) and [Kinesis](https://github.com/exasol/kinesis-connector-extension) into their own repositories are finalized, we are going to update this repository. 

Remove the Kafka and Kinesis parts and update the documentation.

**Comment by morazow** [comment]
I have opened an issue #97, not to forget it.

**Comment by morazow** [comment]
Hello @LennartAtExasol,

We released a new version 0.9.0.

It comes with updated documentation that reflect the changes. Please give it a try!
